dist: xenial
language: generic
cache:
  directories:
    - $HOME/.stack
addons:
  apt:
    packages:
      - libgmp-dev
      - libsndfile1-dev
      - portaudio19-dev

os:
  - linux
  - osx

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - curl -sSL https://get.haskellstack.org/ | sh
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libsndfile portaudio; fi

install:
  - stack --no-terminal --install-ghc test --only-dependencies

script:
  - stack --no-terminal test --ghc-options=-Werror
