dist: xenial
language: generic
cache:
  directories:
    - $HOME/.stack
addons:
  apt:
    packages:
      - libgmp-dev
      - libsndfile1-dev
      - libportaudio19-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack --no-terminal --install-ghc test --only-dependencies

script:
  - stack --no-terminal test --ghc-options=-Werror
