name: loopnaut

source-dirs: src
dependencies:
  - base
ghc-options:
  - -Wall
  - -Wno-name-shadowing

executables:
  loopnaut:
    main: loopnaut-exec.hs
    c-sources:
      - src/loop_buffer.c
    extra-libraries:
      - jack
    dependencies:
      - deepseq
      - directory
      - filepath
      - getopt-generics
      - hinotify
      - hsndfile
      - hsndfile-vector
      - process
      - string-conversions
      - vector

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    c-sources:
      - src/loop_buffer.c
    extra-libraries:
      - jack
    dependencies:
      - bytestring
      - deepseq
      - directory
      - filepath
      - getopt-generics
      - hinotify
      - hsndfile
      - hsndfile-vector
      - hspec
      - interpolate
      - mockery
      - process
      - shake
      - string-conversions
      - vector
