name: loopnaut

source-dirs: src
dependencies:
  - base

executables:
  loopnaut:
    main: Loopnaut.hs
    dependencies:
      - SFML
      - getopt-generics

  generate:
    main: Generate.hs
    dependencies:
      - hsndfile
      - hsndfile-vector
      - random
      - vector

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - bytestring
      - directory
      - filepath
      - hsndfile
      - hsndfile-vector
      - hspec
      - mockery
      - vector
