name: loopnaut

source-dirs: src
dependencies:
  - base

executables:
  loopnaut:
    main: Loopnaut.hs
    dependencies:
      - SFML
      - getopt-generics

  generate:
    main: Generate.hs
    dependencies:
      - hsndfile
      - hsndfile-vector
      - vector
      - random
