name: looper

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -threaded

dependencies:
  - base
  - deepseq
  - directory
  - filepath
  - getopt-generics
  - hsndfile
  - hsndfile-vector
  - process
  - string-conversions
  - vector

source-dirs: src

when:
  condition: os(linux)
  then:
    source-dirs: src/linux
    dependencies:
      - hinotify
  else:
    when:
      condition: os(darwin)
      then:
        source-dirs: src/darwin
        dependencies:
          - hfsevents
      else:
        buildable: false

executables:
  looper:
    main: looper-exec.hs
    c-sources:
      - src/loop_buffer.c
    pkg-config-dependencies: portaudio-2.0

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    c-sources:
      - src/loop_buffer.c
    pkg-config-dependencies: portaudio-2.0
    dependencies:
      - bytestring
      - containers
      - deepseq
      - directory
      - filepath
      - getopt-generics
      - hsndfile
      - hsndfile-vector
      - hspec
      - interpolate
      - mockery
      - process
      - shake
      - silently
      - string-conversions
      - vector
